In [1]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])

test_2 = np.genfromtxt('test_2.csv', delimiter=',')

In [2]:
print(test_2)

[[92. 94. 88. 91. 87.]
 [12. 94. 58. 41. 17.]]


In [3]:
test_2.shape

(2, 5)

In [4]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
test_3_fixed = test_3 + 2

total_grade = test_1 + test_2 + test_3_fixed

final_grade = total_grade / 3

print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [5]:
import numpy as np

student_scores = np.array([[92, 94, 88, 91, 87],
                           [79, 100, 86, 93, 91],
                           [87, 85, 72, 90, 92]])

tanya_test_3 = student_scores[2,0]

cody_test_scores = student_scores[:,4]

In [6]:
import numpy as np

porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]

hot = porridge[porridge > 80]

just_right = porridge[(porridge >= 60) & (porridge <= 80)]

print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]


In [ ]:
import numpy as np

temperatures = np.genfromtxt('temperature_data.csv', delimiter=',')

temperatures_fixed = temperatures + 3

monday_temperatures = temperatures_fixed[0,:]

thursday_friday_morning = temperatures_fixed[3:4+1,1]

temperature_extremes = temperatures_fixed[(temperatures_fixed < 50) | (temperatures_fixed > 60)]

axis=0 are the values that share an index, axis=1 are the values that share an array.

In [7]:
import numpy as np

cupcakes = np.array([2,0.75,2,1,0.5])

recipes = np.genfromtxt('recipes.csv', delimiter=',')

print(recipes)

eggs = recipes[:,2]

(eggs < 1.25) & (eggs > 0.8)

cookies = recipes[2,:]

double_batch = 2 * cupcakes

grocery_list = cookies + double_batch

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [8]:
import numpy as np

store_one = np.array([2, 5, 8, 3, 4, 10, 15, 5])
store_two = np.array([3, 17, 18,  9,  2, 14, 10])
store_three = np.array([7, 5, 4, 3, 2, 7, 7])

store_one_avg = np.mean(store_one)
store_two_avg = np.mean(store_two)
store_three_avg = np.mean(store_three)

print(store_one_avg)
print(store_two_avg)
print(store_three_avg)

best_seller = store_two

6.5
10.428571428571429
5.0


In [9]:
import numpy as np

class_year = np.array([1967, 1949, 2004, 1997, 1953, 1950, 1958, 1974, 1987, 2006, 2013, 1978, 1951, 1998, 1996, 1952, 2005, 2007, 2003, 1955, 1963, 1978, 2001, 2012, 2014, 1948, 1970, 2011, 1962, 1966, 1978, 1988, 2006, 1971, 1994, 1978, 1977, 1960, 2008, 1965, 1990, 2011, 1962, 1995, 2004, 1991, 1952, 2013, 1983, 1955, 1957, 1947, 1994, 1978, 1957, 2016, 1969, 1996, 1958, 1994, 1958, 2008, 1988, 1977, 1991, 1997, 2009, 1976, 1999, 1975, 1949, 1985, 2001, 1952, 1953, 1949, 2015, 2006, 1996, 2015, 2009, 1949, 2004, 2010, 2011, 2001, 1998, 1967, 1994, 1966, 1994, 1986, 1963, 1954, 1963, 1987, 1992, 2008, 1979, 1987])

millennials = np.mean(class_year >= 2005)

print(millennials)

0.21


In [10]:
import numpy as np

allergy_trials = np.array([[6, 1, 3, 8, 2], 
                           [2, 6, 3, 9, 8], 
                           [5, 2, 6, 9, 9]])

total_mean = np.mean(allergy_trials)

trial_mean = np.mean(allergy_trials, axis=1)

patient_mean = np.mean(allergy_trials, axis=0)

print(total_mean)
print(trial_mean)
print(patient_mean)

5.266666666666667
[4.  5.6 6.2]
[4.33333333 3.         4.         8.66666667 6.33333333]
